pipeline {
  agent { label 'kaniko' }

  environment {
    AWS_REGION   = "eu-north-1"
    ECR_REGISTRY = "079662785620.dkr.ecr.eu-north-1.amazonaws.com"
    IMAGE_NAME   = "three-tier-backend"
    IMAGE_TAG    = "${BUILD_NUMBER}"
    SONARQUBE    = "sonarqube"
    GITOPS_REPO  = "https://github.com/faizansayani533/three-tier-gitops.git"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    // ---------------------------
    // SONARQUBE (SAST)
    // ---------------------------
    stage('SonarQube Scan') {
      steps {
        container('sonar-scanner') {
          withSonarQubeEnv("${SONARQUBE}") {
            sh '''
              sonar-scanner \
              -Dsonar.projectKey=three-tier-backend \
              -Dsonar.projectName=three-tier-backend \
              -Dsonar.sources=.
            '''
          }
        }
      }
    }

    stage('Quality Gate') {
      steps {
        timeout(time: 10, unit: 'MINUTES') {
          waitForQualityGate abortPipeline: true
        }
      }
    }

    // ---------------------------
    // OWASP DEPENDENCY CHECK (SCA)
    // ---------------------------
    stage('Prepare Dependency-Check DB') {
      steps {
        container('dependency-check') {
          withCredentials([string(credentialsId: 'nvd-api-key', variable: 'NVD_API_KEY')]) {
            sh '''
              if [ ! -d "/odc-data/nvdcve" ]; then
                /usr/share/dependency-check/bin/dependency-check.sh \
                  --updateonly \
                  --data /odc-data \
                  --nvdApiKey $NVD_API_KEY
              else
                echo "Using cached ODC DB"
              fi
            '''
          }
        }
      }
    }

    stage('OWASP Dependency Check') {
      steps {
        container('dependency-check') {
          sh '''
            rm -rf dc-report
            mkdir dc-report

            /usr/share/dependency-check/bin/dependency-check.sh \
              --project three-tier-backend \
              --scan . \
              --format HTML \
              --out dc-report \
              --disableAssembly \
              --data /odc-data \
              --noupdate || true
          '''
        }
      }
    }

    // ---------------------------
    // GITLEAKS (SECRETS SCAN)
    // ---------------------------
    stage('GitLeaks Scan') {
      steps {
        container('gitleaks') {
          sh '''
            gitleaks detect \
              --source . \
              --report-format json \
              --report-path gitleaks-report.json \
              --no-git || true
          '''
        }
      }
    }

    // ---------------------------
    // BUILD & PUSH IMAGE
    // ---------------------------
    stage('Build & Push Image (Kaniko)') {
      steps {
        container('kaniko') {
          sh '''
            /kaniko/executor \
              --context /home/jenkins/agent/workspace/three-tier-backend \
              --dockerfile /home/jenkins/agent/workspace/three-tier-backend/Dockerfile \
              --destination $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG \
              --destination $ECR_REGISTRY/$IMAGE_NAME:latest \
              --verbosity=info
          '''
        }
      }
    }

  // ---------------------------
    // TRIVY IMAGE SCAN (NON BLOCKING)
    // ---------------------------
stage('Trivy Scan') {
  steps {
    container('trivy') {
      sh '''
        echo "🔍 Running Trivy image scan..."

        trivy image \
          --format template \
	  --template "@/contrib/html.tpl" \
          --output trivy-report.html \
          --severity CRITICAL,HIGH \
          --no-progress \
          $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG || true
      '''
    }
  }
}

    // ---------------------------
    // UPDATE GITOPS REPO
    // ---------------------------
    stage('Update GitOps Repo') {
      steps {
        withCredentials([string(credentialsId: 'gitops-token', variable: 'GIT_TOKEN')]) {
          sh '''
            rm -rf gitops
            git clone https://$GIT_TOKEN@github.com/faizansayani533/three-tier-gitops.git gitops
            cd gitops/backend

            sed -i "s|image: .*|image: $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG|g" deployment.yaml

            git config user.email "jenkins@devsecops.local"
            git config user.name "Jenkins CI"

            git add deployment.yaml
            git commit -m "Backend image updated to $IMAGE_TAG"
            git push origin main
          '''
        }
      }
    }
 // ---------------------------
    // OWASP ZAP DAST SCAN (NON BLOCKING)
    // ---------------------------
stage('OWASP ZAP DAST Scan') {
  steps {
    container('zap') {
      sh '''
        echo "🚨 Running OWASP ZAP scan..."

        mkdir -p /zap/wrk

        zap-baseline.py \
          -t http://a998a5c39b13c427ebf3a09def396192-1140351167.eu-north-1.elb.amazonaws.com \
          -r zap.html || true

        cp /zap/wrk/zap.html .
      '''
    }
  }
}

  }

  post {

    always {
	echo "📦 Archiving security reports..."
    archiveArtifacts artifacts: 'zap.html, trivy-report.html, dc-report/**,gitleaks-report.*', fingerprint: true
    }

    success {
      echo "✅ FRONTEND PIPELINE PASSED — Argo CD will deploy UI"
    }

    failure {
      echo "❌ FRONTEND PIPELINE COMPLETED WITH SECURITY FAILURES"
    }
  }
}
